[2024-08-03T22:12:00.231+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T22:12:00.379+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.run_extraction scheduled__2024-08-03T00:00:00+00:00 [queued]>
[2024-08-03T22:12:00.415+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.run_extraction scheduled__2024-08-03T00:00:00+00:00 [queued]>
[2024-08-03T22:12:00.417+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-03T22:12:00.572+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_extraction> on 2024-08-03 00:00:00+00:00
[2024-08-03T22:12:00.582+0000] {standard_task_runner.py:64} INFO - Started process 191 to run task
[2024-08-03T22:12:00.607+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag', 'run_extraction', 'scheduled__2024-08-03T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp_09w9oc8']
[2024-08-03T22:12:00.634+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask run_extraction
[2024-08-03T22:12:00.935+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.run_extraction scheduled__2024-08-03T00:00:00+00:00 [running]> on host 9c49d916f31b
[2024-08-03T22:12:01.450+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='run_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-03T00:00:00+00:00'
[2024-08-03T22:12:01.452+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T22:12:01.498+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-03T22:12:01.520+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python usr/local/airflow/src/extraction.py']
[2024-08-03T22:12:01.536+0000] {subprocess.py:86} INFO - Output:
[2024-08-03T22:12:01.735+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/airflowtmpa2qvw9e6/usr/local/airflow/src/extraction.py': [Errno 2] No such file or directory
[2024-08-03T22:12:01.738+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-08-03T22:12:01.739+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T22:12:01.786+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-03T22:12:01.842+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag, task_id=run_extraction, run_id=scheduled__2024-08-03T00:00:00+00:00, execution_date=20240803T000000, start_date=20240803T221200, end_date=20240803T221201
[2024-08-03T22:12:02.200+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task run_extraction (Bash command failed. The command returned a non-zero exit code 2.; 191)
[2024-08-03T22:12:02.215+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-03T22:12:02.265+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T22:12:02.429+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
